spring:
  application:
    name: eamon-eureka-slaveone
  profiles:
    active: slaveone
eureka:
  instance:
    # 设置当前实例的主机名称
    hostname: localhost
  client:
    # 由于该应用为注册中心，所以设置为false，代表不向注册中心注册自己
    register-with-eureka: false
    # 由于注册中心的职责就是维护服务实例，他并不需要去检索服务，所以也设置为false
    fetch-registry: false
  server:
    # 关闭自我保护
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 6000
security:
  basic:
    enabled: true
  user:
    name: eamon
    password: eamon
